AppBundle\Entity\Caja:
    type: entity
    table: cajas
    indexes:
        id_persona:
            columns:
                - id_persona
    id:
        idCaja:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_caja
            generator:
                strategy: IDENTITY
    fields:
        idPersona:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_persona
        fechaCaja:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: fecha_caja
        activa:
            type: boolean
            nullable: false
            options:
                default: '1'
    lifecycleCallbacks: {  }
