AppBundle\Entity\Genero:
    type: entity
    table: generos
    uniqueConstraints:
        descripcion:
            columns:
                - descripcion
    id:
        idGenero:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_genero
            generator:
                strategy: IDENTITY
    fields:
        descripcion:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        activo:
            type: boolean
            nullable: false
            options:
                default: '1'
    lifecycleCallbacks: {  }
