AppBundle\Entity\Producto:
    type: entity
    table: productos
    uniqueConstraints:
        descripcion:
            columns:
                - descripcion
    id:
        idProducto:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_producto
            generator:
                strategy: IDENTITY
    fields:
        descripcion:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        activo:
            type: boolean
            nullable: false
            options:
                default: '1'
    lifecycleCallbacks: {  }
